apiVersion: apps/v1
kind: Deployment

metadata:
  name: enterprise-api

spec:
  replicas: 2

  selector:
    matchLabels:
      app: enterprise-api

  template:
    metadata:
      labels:
        app: enterprise-api

    spec:
      containers:
      - name: enterprise-api
        image: enterprise-api:v1

        imagePullPolicy: Never

        ports:
        - containerPort: 8081
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: enterprise-api-config
              key: APP_ENV

        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: enterprise-api-config
              key: APP_NAME

        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: enterprise-api-config
              key: LOG_LEVEL

        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: enterprise-api-secret
              key: DB_USERNAME

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: enterprise-api-secret
              key: DB_PASSWORD
